(async function(){
  var APP='/arbeitsbereiche/A5604057339/LAB_Apps/LageInfo';
  var LIST='LageInfo_Vorkommnisse';
  var WEB=(window._spPageContextInfo&&_spPageContextInfo.webAbsoluteUrl)||location.origin+'/arbeitsbereiche/A5604057339';
  function log(m){console.log('%c[LageInfo] '+m,'color:#22d3ee;font-weight:bold')}
  function fail(m,e){console.error('[LageInfo] '+m,e||'');alert('LageInfo: '+m+(e&&e.message?'\n'+e.message:''))}
  async function req(url,opt){opt=opt||{};opt.credentials='same-origin';opt.headers=Object.assign({Accept:'application/json;odata=verbose'},opt.headers||{});return fetch(url,opt)}
  async function digest(){var el=document.getElementById('__REQUESTDIGEST')||document.querySelector('input[name="__REQUESTDIGEST"]');if(el&&el.value){log('RequestDigest aus Seite gefunden ✓');return el.value}log('Kein RequestDigest in Seite, contextinfo wird abgefragt ...');var r=await fetch(WEB+'/_api/contextinfo',{method:'POST',credentials:'same-origin',headers:{Accept:'application/json;odata=verbose','Content-Type':'application/json;odata=verbose'}});if(!r.ok)throw Error('contextinfo HTTP '+r.status+' '+(await r.text()).slice(0,300));var text=await r.text(),value='';try{var j=JSON.parse(text);value=(j&&j.d&&j.d.GetContextWebInformation&&j.d.GetContextWebInformation.FormDigestValue)||(j&&j.FormDigestValue)||(j&&j.GetContextWebInformation&&j.GetContextWebInformation.FormDigestValue)||''}catch(e){}if(!value&&text.indexOf('<')>=0){try{var xml=new DOMParser().parseFromString(text,'text/xml');var nodes=xml.getElementsByTagName('*');for(var i=0;i<nodes.length;i++){if((nodes[i].localName||nodes[i].nodeName).replace(/^.*:/,'')==='FormDigestValue'){value=(nodes[i].textContent||'').trim();break}}}catch(e){}}if(!value){var m=text.match(/<[^>]*FormDigestValue[^>]*>([^<]+)</i);if(m)value=m[1].trim()}if(!value)throw Error('contextinfo lieferte keinen FormDigestValue. Antwort beginnt mit: '+text.slice(0,180).replace(/\s+/g,' '));log('RequestDigest aus contextinfo gelesen ✓');return value}
  async function ensureList(d){log('Liste '+LIST+' prüfen ...');var base=WEB+'/_api/web/lists';var r=await req(base+"/getbytitle('"+LIST+"')?$select=Id,Title");if(r.ok){log('Liste vorhanden ✓');return}if(r.status!==404)throw Error('Listenprüfung HTTP '+r.status+' '+(await r.text()).slice(0,300));log('Liste fehlt, wird erstellt ...');r=await req(base,{method:'POST',headers:{'Content-Type':'application/json;odata=verbose','X-RequestDigest':d},body:JSON.stringify({__metadata:{type:'SP.List'},BaseTemplate:100,Title:LIST,Description:'LageInfo: manuell erfasste Vorkommnisse und Lagewerte'})});if(!r.ok)throw Error('Listenerstellung HTTP '+r.status+' '+(await r.text()).slice(0,500));log('Liste erstellt ✓')}
  async function fieldExists(title){var url=WEB+"/_api/web/lists/getbytitle('"+LIST+"')/fields?$select=Title,InternalName";var r=await req(url);if(!r.ok)throw Error('Feldliste HTTP '+r.status+' '+(await r.text()).slice(0,300));var text=await r.text(),arr=[];try{var j=JSON.parse(text);arr=(j&&j.d&&j.d.results)||(j&&j.value)||[]}catch(e){throw Error('Feldliste konnte nicht gelesen werden: '+text.slice(0,200))}var wanted=String(title).toLowerCase();return arr.some(function(f){return String(f.Title||'').toLowerCase()===wanted||String(f.InternalName||'').toLowerCase()===wanted})}
  async function ensureFields(d){var defs=[['ObjektID','Text'],['Objektname','Text'],['Objekttyp','Choice'],['LayerKey','Text'],['Kategorie','Choice'],['Lagewert','Choice'],['Kurzbeschreibung','Note'],['Ereignisdatum','DateTime'],['Status','Choice'],['Quelle','Text']];var choices={Objekttyp:['Bundesland','Landkreis','Gemeinde / Stadt','Stadtteil / Bezirk','Liegenschaft','Standortübungsplatz','Truppenübungsplatz'],Kategorie:['Sabotage','Drohne','Spionage','Terror / Extremismus','Cyberangriff','Bundeswehr-Bezug','Hybride Bedrohung','Demo / Kundgebung'],Lagewert:['Gelb - erhöht','Orange - hoch','Rot - sehr hoch'],Status:['Aktiv','Beobachtung','Erledigt']};for(var i=0;i<defs.length;i++){var title=defs[i][0],type=defs[i][1];log('Spalte '+title+' prüfen ...');if(await fieldExists(title)){log('Spalte '+title+' vorhanden ✓');continue}log('Spalte '+title+' fehlt, wird erstellt ...');var schema;if(type==='Choice')schema='<Field DisplayName="'+title+'" Name="'+title+'" StaticName="'+title+'" Type="Choice" Format="Dropdown"><CHOICES>'+choices[title].map(function(c){return '<CHOICE>'+c+'</CHOICE>'}).join('')+'</CHOICES></Field>';else if(type==='Note')schema='<Field DisplayName="'+title+'" Name="'+title+'" StaticName="'+title+'" Type="Note" NumLines="6" RichText="FALSE" />';else if(type==='DateTime')schema='<Field DisplayName="'+title+'" Name="'+title+'" StaticName="'+title+'" Type="DateTime" Format="DateTime" />';else schema='<Field DisplayName="'+title+'" Name="'+title+'" StaticName="'+title+'" Type="Text" MaxLength="255" />';var r=await req(WEB+"/_api/web/lists/getbytitle('"+LIST+"')/fields/createfieldasxml",{method:'POST',headers:{'Content-Type':'application/json;odata=verbose','X-RequestDigest':d},body:JSON.stringify({parameters:{__metadata:{type:'SP.XmlSchemaFieldCreationInformation'},SchemaXml:schema,Options:0}})});if(!r.ok)throw Error('Spalte '+title+' HTTP '+r.status+' '+(await r.text()).slice(0,500));log('Spalte '+title+' erstellt ✓')}}
  try{log('Start. Web: '+WEB);var d=await digest();await ensureList(d);await ensureFields(d);log('PROVISIONIERUNG FERTIG ✓');alert('LageInfo: Liste und Spalten sind bereit.');var r=await fetch(APP+'/index.html',{credentials:'same-origin',cache:'no-store'});if(!r.ok)throw Error('index.html HTTP '+r.status);log('index.html erreichbar ✓')}catch(e){fail('Einrichtung abgebrochen',e)}
})();