(async function(){
  var APP='/arbeitsbereiche/A5604057339/LAB_Apps/LageInfo';
  var LIST='LageInfo_Vorkommnisse';
  var WEB=(window._spPageContextInfo&&_spPageContextInfo.webAbsoluteUrl)||location.origin+location.pathname.split('/LAB_Apps/')[0];
  function log(msg){console.log('%c[LageInfo] '+msg,'color:#22d3ee;font-weight:bold')}
  function fail(msg,e){console.error('[LageInfo] '+msg,e||'');alert('LageInfo: '+msg+(e&&e.message?'\n'+e.message:''))}
  async function req(url,opt){opt=opt||{};opt.credentials='same-origin';opt.headers=Object.assign({Accept:'application/json;odata=verbose'},opt.headers||{});var r=await fetch(url,opt);return r}
  async function digest(){log('SharePoint RequestDigest anfordern ...');var r=await req(WEB+'/_api/contextinfo',{method:'POST'});if(!r.ok)throw Error('contextinfo HTTP '+r.status);var j=await r.json();log('RequestDigest OK');return j.d.GetContextWebInformation.FormDigestValue}
  async function ensureList(){log('Liste '+LIST+' prüfen ...');var base=WEB+'/_api/web/lists';var r=await req(base+"/getbytitle('"+LIST+"')");if(r.ok){log('Liste vorhanden ✓');return}if(r.status!==404)throw Error('Listenprüfung HTTP '+r.status);log('Liste fehlt, wird erstellt ...');var d=await digest();r=await req(base,{method:'POST',headers:{'Content-Type':'application/json;odata=verbose','X-RequestDigest':d},body:JSON.stringify({__metadata:{type:'SP.List'},BaseTemplate:100,Title:LIST,Description:'LageInfo: manuell erfasste Vorkommnisse und Lagewerte'})});if(!r.ok)throw Error('Listenerstellung HTTP '+r.status+' '+await r.text());log('Liste erstellt ✓')}
  async function ensureFields(){var defs=[['ObjektID','Text'],['Objektname','Text'],['Objekttyp','Choice'],['Kategorie','Choice'],['Lagewert','Choice'],['Kurzbeschreibung','Note'],['Ereignisdatum','DateTime'],['Status','Choice'],['Quelle','Text']];var choices={Objekttyp:['Bundesland','Landkreis','Gemeinde / Stadt','Stadtteil / Bezirk','Liegenschaft','Standortübungsplatz','Truppenübungsplatz'],Kategorie:['Sabotage','Drohne','Spionage','Terror / Extremismus','Cyberangriff','Bundeswehr-Bezug','Hybride Bedrohung','Demo / Kundgebung'],Lagewert:['Gelb - erhöht','Orange - hoch','Rot - sehr hoch'],Status:['Aktiv','Beobachtung','Erledigt']};var d=await digest();for(var i=0;i<defs.length;i++){var title=defs[i][0],type=defs[i][1];log('Spalte '+title+' prüfen ...');var fieldUrl=WEB+"/_api/web/lists/getbytitle('"+LIST+"')/fields/getbytitle('"+title+"')";var r=await req(fieldUrl);if(r.ok){log('Spalte '+title+' vorhanden ✓');continue}if(r.status!==404)throw Error('Spaltenprüfung '+title+' HTTP '+r.status);var schema;if(type==='Choice')schema='<Field DisplayName="'+title+'" Name="'+title+'" Type="Choice" Format="Dropdown"><CHOICES>'+choices[title].map(function(c){return '<CHOICE>'+c+'</CHOICE>'}).join('')+'</CHOICES></Field>';else if(type==='Note')schema='<Field DisplayName="'+title+'" Name="'+title+'" Type="Note" NumLines="6" RichText="FALSE" />';else if(type==='DateTime')schema='<Field DisplayName="'+title+'" Name="'+title+'" Type="DateTime" Format="DateTime" />';else schema='<Field DisplayName="'+title+'" Name="'+title+'" Type="Text" MaxLength="255" />';r=await req(WEB+"/_api/web/lists/getbytitle('"+LIST+"')/fields/createfieldasxml",{method:'POST',headers:{'Content-Type':'application/json;odata=verbose','X-RequestDigest':d},body:JSON.stringify({parameters:{__metadata:{type:'SP.XmlSchemaFieldCreationInformation'},SchemaXml:schema,Options:0}})});if(!r.ok)throw Error('Spalte '+title+' HTTP '+r.status+' '+await r.text());log('Spalte '+title+' erstellt ✓')}}
  try{log('Start. Web: '+WEB);await ensureList();await ensureFields();log('PROVISIONIERUNG FERTIG ✓');alert('LageInfo: Liste und Spalten sind bereit.');log('index.html wird geprüft ...');var r=await req(APP+'/index.html',{cache:'no-store'});if(!r.ok)throw Error('index.html HTTP '+r.status);log('index.html erreichbar ✓');log('Fertig. Die SharePoint-Seite bleibt für die Kontrolle geöffnet.');}catch(e){fail('Einrichtung abgebrochen',e)}
})();