(async function(){
  var APP='/arbeitsbereiche/A5604057339/LAB_Apps/LageInfo';
  var LIST='LageInfo_Vorkommnisse';
  var WEB=(window._spPageContextInfo&&_spPageContextInfo.webAbsoluteUrl)||location.origin+'/arbeitsbereiche/A5604057339';
  function log(m){console.log('%c[LageInfo] '+m,'color:#22d3ee;font-weight:bold')}
  function fail(m,e){console.error('[LageInfo] '+m,e||'');alert('LageInfo: '+m+(e&&e.message?'\n'+e.message:''))}
  async function req(url,opt){opt=opt||{};opt.credentials='same-origin';opt.headers=Object.assign({Accept:'application/json;odata=nometadata'},opt.headers||{});return fetch(url,opt)}
  function digest(){var el=document.getElementById('__REQUESTDIGEST')||document.querySelector('input[name="__REQUESTDIGEST"]');if(!el||!el.value)throw Error('__REQUESTDIGEST wurde auf dieser SharePoint-Seite nicht gefunden. Bitte das Script auf einer normalen Seite des Arbeitsbereichs ausführen.');log('SharePoint FormDigest gefunden ✓');return el.value}
  async function ensureList(){log('Liste '+LIST+' prüfen ...');var base=WEB+'/_api/web/lists';var r=await req(base+"/getbytitle('"+LIST+"')?$select=Id,Title");if(r.ok){log('Liste vorhanden ✓');return}if(r.status!==404)throw Error('Listenprüfung HTTP '+r.status+' '+(await r.text()).slice(0,300));log('Liste fehlt, wird erstellt ...');r=await req(base,{method:'POST',headers:{'Content-Type':'application/json;odata=nometadata','X-RequestDigest':digest()},body:JSON.stringify({BaseTemplate:100,Title:LIST,Description:'LageInfo: manuell erfasste Vorkommnisse und Lagewerte'})});if(!r.ok)throw Error('Listenerstellung HTTP '+r.status+' '+(await r.text()).slice(0,500));log('Liste erstellt ✓')}
  async function ensureFields(){var defs=[['ObjektID','Text'],['Objektname','Text'],['Objekttyp','Choice'],['Kategorie','Choice'],['Lagewert','Choice'],['Kurzbeschreibung','Note'],['Ereignisdatum','DateTime'],['Status','Choice'],['Quelle','Text']];var choices={Objekttyp:['Bundesland','Landkreis','Gemeinde / Stadt','Stadtteil / Bezirk','Liegenschaft','Standortübungsplatz','Truppenübungsplatz'],Kategorie:['Sabotage','Drohne','Spionage','Terror / Extremismus','Cyberangriff','Bundeswehr-Bezug','Hybride Bedrohung','Demo / Kundgebung'],Lagewert:['Gelb - erhöht','Orange - hoch','Rot - sehr hoch'],Status:['Aktiv','Beobachtung','Erledigt']};var d=digest();for(var i=0;i<defs.length;i++){var title=defs[i][0],type=defs[i][1];log('Spalte '+title+' prüfen ...');var r=await req(WEB+"/_api/web/lists/getbytitle('"+LIST+"')/fields?$select=Title&$filter=Title eq '"+encodeURIComponent(title)+"'");if(r.ok){var txt=await r.text(),exists=false;try{var j=JSON.parse(txt);exists=Array.isArray(j.value)?j.value.length>0:!!(j.d&&j.d.results&&j.d.results.length)}catch(e){}if(exists){log('Spalte '+title+' vorhanden ✓');continue}}var schema;if(type==='Choice')schema='<Field DisplayName="'+title+'" Name="'+title+'" Type="Choice" Format="Dropdown"><CHOICES>'+choices[title].map(function(c){return '<CHOICE>'+c+'</CHOICE>'}).join('')+'</CHOICES></Field>';else if(type==='Note')schema='<Field DisplayName="'+title+'" Name="'+title+'" Type="Note" NumLines="6" RichText="FALSE" />';else if(type==='DateTime')schema='<Field DisplayName="'+title+'" Name="'+title+'" Type="DateTime" Format="DateTime" />';else schema='<Field DisplayName="'+title+'" Name="'+title+'" Type="Text" MaxLength="255" />';r=await req(WEB+"/_api/web/lists/getbytitle('"+LIST+"')/fields/createfieldasxml",{method:'POST',headers:{'Content-Type':'application/json;odata=nometadata','X-RequestDigest':d},body:JSON.stringify({parameters:{SchemaXml:schema,Options:0}})});if(!r.ok)throw Error('Spalte '+title+' HTTP '+r.status+' '+(await r.text()).slice(0,500));log('Spalte '+title+' erstellt ✓')}}
  try{log('Start. Web: '+WEB);digest();await ensureList();await ensureFields();log('PROVISIONIERUNG FERTIG ✓');alert('LageInfo: Liste und Spalten sind bereit.');var r=await req(APP+'/index.html',{cache:'no-store'});if(!r.ok)throw Error('index.html HTTP '+r.status);log('index.html erreichbar ✓')}catch(e){fail('Einrichtung abgebrochen',e)}
})();